### ISSUE TITLE
Feature request: popup file picker after press enter in telescope to select a folder 

### ISSUE THREAD

**Issue by AllenDang** [marcuscaisey/olddirs.nvim#1]
Here is an ideal workflow:
1. Invoke olddirs telescope picker.
2. Press enter to select a folder, telescope picker close.
3. A new telescope file picker popup, prompts to select a file within that folder to open.

This is what I do all day with workspaces.

**Comment by marcuscaisey** [comment]
This can be achieved by providing either of the `selected_dir_callback` or `attach_mappings` options to the picker. There weren't any examples of this in the docs though so i've added some now. See the [Example Mappings](https://github.com/marcuscaisey/olddirs.nvim/blob/master/README.md#example-mappings) section of the `README` or do a `:help olddirs-example-mappings`.
